worker_threads = 4
close_timeout = 30
exit_timeout = 30
shutdown_grace_period = 60 # in seconds


[[services]]
name = "default.default.serviceaccount.identity.umay.cluster.local"
port = 9994
cert_path = ""
key_path = ""
ca_path = ""
upstream_host = "localhost"
upstream_port = 1994
discovery_type = "dns"
discovery_refresh_interval = 300
load_balancer_selection = "round_robin"

